-- MySQL 8.0+ schema — port of the Supabase/Postgres corebank schema.
-- All FKs use ON DELETE RESTRICT for safety. RLS is replaced by app-layer checks.
-- UUIDs are CHAR(36) and generated by the application (crypto.randomUUID()).

SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- ============================================================
-- AUTH (replaces Supabase auth.users + auth.mfa_factors)
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  email           VARCHAR(255) NOT NULL,
  full_name       VARCHAR(255) NOT NULL,
  password_hash   VARCHAR(255) NOT NULL,
  mfa_secret      VARCHAR(64)      NULL,
  mfa_enrolled    TINYINT(1)   NOT NULL DEFAULT 0,
  is_active       TINYINT(1)   NOT NULL DEFAULT 1,
  created_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_users_email (email)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS refresh_tokens (
  jti         CHAR(36)    NOT NULL PRIMARY KEY,
  user_id     CHAR(36)    NOT NULL,
  mfa         TINYINT(1)  NOT NULL DEFAULT 0,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  revoked_at  DATETIME(3)     NULL,
  KEY ix_rt_user (user_id),
  CONSTRAINT fk_rt_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- PROFILES + ROLES + PERMISSIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS profiles (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  full_name    VARCHAR(255) NOT NULL,
  email        VARCHAR(255)     NULL,
  branch       VARCHAR(255)     NULL,
  is_active    TINYINT(1)   NOT NULL DEFAULT 1,
  mfa_required TINYINT(1)   NOT NULL DEFAULT 0,
  created_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at   DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_profiles_user FOREIGN KEY (id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_roles (
  id         CHAR(36)    NOT NULL PRIMARY KEY,
  user_id    CHAR(36)    NOT NULL,
  role       ENUM('super_admin','admin','manager','teller','loan_officer','finance_officer','auditor') NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_user_role (user_id, role),
  CONSTRAINT fk_ur_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS permissions (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  code        VARCHAR(100) NOT NULL,
  description VARCHAR(500)     NULL,
  category    VARCHAR(100)     NULL,
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_perm_code (code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS role_permissions (
  id            CHAR(36)    NOT NULL PRIMARY KEY,
  role          ENUM('super_admin','admin','manager','teller','loan_officer','finance_officer','auditor') NOT NULL,
  permission_id CHAR(36)    NOT NULL,
  created_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_rp (role, permission_id),
  CONSTRAINT fk_rp_perm FOREIGN KEY (permission_id) REFERENCES permissions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- CUSTOMERS + PII VAULT + KYC + GUARANTORS
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
  id                    CHAR(36)       NOT NULL PRIMARY KEY,
  customer_number       VARCHAR(50)    NOT NULL,
  customer_type         ENUM('individual','business') NOT NULL DEFAULT 'individual',
  full_name             VARCHAR(255)   NOT NULL,
  national_id           VARCHAR(50)        NULL,
  date_of_birth         DATE               NULL,
  email                 VARCHAR(255)       NULL,
  phone                 VARCHAR(50)        NULL,
  address               TEXT               NULL,
  city                  VARCHAR(100)       NULL,
  country               VARCHAR(100)   NOT NULL DEFAULT 'Kenya',
  occupation            VARCHAR(255)       NULL,
  employer              VARCHAR(255)       NULL,
  monthly_income        DECIMAL(18,2)      NULL,
  kyc_status            ENUM('pending','submitted','verified','rejected') NOT NULL DEFAULT 'pending',
  kyc_notes             TEXT               NULL,
  kyc_submitted_by      CHAR(36)           NULL,
  kyc_submitted_at      DATETIME(3)        NULL,
  kyc_verified_by       CHAR(36)           NULL,
  kyc_verified_at       DATETIME(3)        NULL,
  kyc_rejection_reason  TEXT               NULL,
  credit_score          INT            NOT NULL DEFAULT 650,
  is_active             TINYINT(1)     NOT NULL DEFAULT 1,
  created_by            CHAR(36)           NULL,
  created_at            DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at            DATETIME(3)    NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_customer_number (customer_number),
  KEY ix_customers_kyc (kyc_status),
  KEY ix_customers_phone (phone),
  CONSTRAINT fk_cust_creator      FOREIGN KEY (created_by)       REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cust_kyc_sub      FOREIGN KEY (kyc_submitted_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_cust_kyc_ver      FOREIGN KEY (kyc_verified_by)  REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS customer_pii_vault (
  customer_id      CHAR(36)    NOT NULL PRIMARY KEY,
  national_id_enc  VARBINARY(512)  NULL,
  phone_enc        VARBINARY(512)  NULL,
  email_enc        VARBINARY(512)  NULL,
  dob_enc          VARBINARY(512)  NULL,
  updated_at       DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_pii_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS kyc_documents (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  customer_id     CHAR(36)     NOT NULL,
  doc_type        VARCHAR(100) NOT NULL,
  storage_path    VARCHAR(500) NOT NULL,
  is_id_document  TINYINT(1)   NOT NULL DEFAULT 0,
  uploaded_by     CHAR(36)         NULL,
  uploaded_at     DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_kyc_cust (customer_id),
  CONSTRAINT fk_kyc_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_kyc_user FOREIGN KEY (uploaded_by) REFERENCES users(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS guarantors (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  customer_id     CHAR(36)     NOT NULL,
  full_name       VARCHAR(255) NOT NULL,
  national_id     VARCHAR(50)  NOT NULL,
  phone           VARCHAR(50)  NOT NULL,
  email           VARCHAR(255)     NULL,
  relationship    VARCHAR(100)     NULL,
  address         TEXT             NULL,
  occupation      VARCHAR(255)     NULL,
  monthly_income  DECIMAL(18,2)    NULL,
  notes           TEXT             NULL,
  created_by      CHAR(36)         NULL,
  created_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY ix_guar_cust (customer_id),
  CONSTRAINT fk_guar_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_guar_user FOREIGN KEY (created_by)  REFERENCES users(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- ACCOUNTS + TRANSACTIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS accounts (
  id             CHAR(36)      NOT NULL PRIMARY KEY,
  account_number VARCHAR(50)   NOT NULL,
  account_type   ENUM('savings','current','loan','wallet') NOT NULL,
  customer_id    CHAR(36)      NOT NULL,
  currency       VARCHAR(8)    NOT NULL DEFAULT 'KES',
  balance        DECIMAL(18,2) NOT NULL DEFAULT 0,
  interest_rate  DECIMAL(7,4)      NULL DEFAULT 0,
  status         ENUM('active','dormant','closed','frozen') NOT NULL DEFAULT 'active',
  opened_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at     DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_account_number (account_number),
  KEY ix_acc_cust (customer_id),
  CONSTRAINT fk_acc_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS transactions (
  id                       CHAR(36)      NOT NULL PRIMARY KEY,
  reference                VARCHAR(100)  NOT NULL,
  txn_type                 ENUM('deposit','withdrawal','transfer','fee','interest','reversal','disbursement','repayment') NOT NULL,
  amount                   DECIMAL(18,2) NOT NULL,
  status                   ENUM('pending','completed','failed','reversed') NOT NULL DEFAULT 'completed',
  description              TEXT              NULL,
  account_id               CHAR(36)          NULL,
  counterparty_account_id  CHAR(36)          NULL,
  performed_by             CHAR(36)          NULL,
  created_at               DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_tx_account (account_id),
  KEY ix_tx_created (created_at),
  CONSTRAINT fk_tx_acc       FOREIGN KEY (account_id)              REFERENCES accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_tx_counter   FOREIGN KEY (counterparty_account_id) REFERENCES accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_tx_user      FOREIGN KEY (performed_by)            REFERENCES users(id)    ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- LOANS + REPAYMENTS + RESTRUCTURES + WRITEOFFS + PROVISIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS loans (
  id                            CHAR(36)      NOT NULL PRIMARY KEY,
  loan_number                   VARCHAR(50)   NOT NULL,
  customer_id                   CHAR(36)      NOT NULL,
  account_id                    CHAR(36)          NULL,
  principal                     DECIMAL(18,2) NOT NULL,
  interest_rate                 DECIMAL(7,4)  NOT NULL,
  term_months                   INT           NOT NULL,
  method                        ENUM('flat','reducing_balance','daily_accrual') NOT NULL DEFAULT 'reducing_balance',
  status                        ENUM('draft','pending','approved','rejected','disbursed','active','in_arrears','closed') NOT NULL DEFAULT 'pending',
  purpose                       TEXT              NULL,
  rejection_reason              TEXT              NULL,
  outstanding_balance           DECIMAL(18,2) NOT NULL DEFAULT 0,
  late_fees                     DECIMAL(18,2) NOT NULL DEFAULT 0,
  mpesa_charge                  DECIMAL(18,2) NOT NULL DEFAULT 0,
  rollover_of                   CHAR(36)          NULL,
  disbursement_date             DATE              NULL,
  due_date                      DATE              NULL,
  next_payment_date             DATE              NULL,
  projected_payment_date        DATE              NULL,
  disbursed_at                  DATETIME(3)       NULL,
  submitted_for_approval_at     DATETIME(3)       NULL,
  approved_by                   CHAR(36)          NULL,
  created_by                    CHAR(36)          NULL,
  created_at                    DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at                    DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_loan_number (loan_number),
  KEY ix_loan_cust   (customer_id),
  KEY ix_loan_status (status),
  KEY ix_loan_due    (due_date),
  CONSTRAINT fk_loan_cust   FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE RESTRICT,
  CONSTRAINT fk_loan_acc    FOREIGN KEY (account_id)  REFERENCES accounts(id)  ON DELETE SET NULL,
  CONSTRAINT fk_loan_roll   FOREIGN KEY (rollover_of) REFERENCES loans(id)     ON DELETE SET NULL,
  CONSTRAINT fk_loan_appr   FOREIGN KEY (approved_by) REFERENCES users(id)     ON DELETE SET NULL,
  CONSTRAINT fk_loan_creator FOREIGN KEY (created_by) REFERENCES users(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_repayments (
  id                    CHAR(36)      NOT NULL PRIMARY KEY,
  loan_id               CHAR(36)      NOT NULL,
  reference             VARCHAR(100)  NOT NULL,
  amount                DECIMAL(18,2) NOT NULL,
  paid_at               DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  posted_by             CHAR(36)          NULL,
  allocated_principal   DECIMAL(18,2) NOT NULL DEFAULT 0,
  allocated_interest    DECIMAL(18,2) NOT NULL DEFAULT 0,
  allocated_fees        DECIMAL(18,2) NOT NULL DEFAULT 0,
  allocated_penalty     DECIMAL(18,2) NOT NULL DEFAULT 0,
  reversed              TINYINT(1)    NOT NULL DEFAULT 0,
  reversed_by           CHAR(36)          NULL,
  reversed_at           DATETIME(3)       NULL,
  reversal_reason       TEXT              NULL,
  created_at            DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_rep_loan (loan_id),
  KEY ix_rep_paid (paid_at),
  CONSTRAINT fk_rep_loan     FOREIGN KEY (loan_id)     REFERENCES loans(id) ON DELETE RESTRICT,
  CONSTRAINT fk_rep_poster   FOREIGN KEY (posted_by)   REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_rep_reverser FOREIGN KEY (reversed_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_restructures (
  id                  CHAR(36)      NOT NULL PRIMARY KEY,
  loan_id             CHAR(36)      NOT NULL,
  reason              TEXT          NOT NULL,
  new_due_date        DATE          NOT NULL,
  new_term_months     INT               NULL,
  new_interest_rate   DECIMAL(7,4)      NULL,
  status              ENUM('pending','approved','rejected','applied') NOT NULL DEFAULT 'pending',
  requested_by        CHAR(36)          NULL,
  requested_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  approved_by         CHAR(36)          NULL,
  approved_at         DATETIME(3)       NULL,
  applied_at          DATETIME(3)       NULL,
  rejection_reason    TEXT              NULL,
  created_at          DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at          DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY ix_rs_loan   (loan_id),
  KEY ix_rs_status (status),
  CONSTRAINT fk_rs_loan      FOREIGN KEY (loan_id)      REFERENCES loans(id) ON DELETE CASCADE,
  CONSTRAINT fk_rs_requester FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_rs_approver  FOREIGN KEY (approved_by)  REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_writeoffs (
  id                CHAR(36)      NOT NULL PRIMARY KEY,
  loan_id           CHAR(36)      NOT NULL,
  amount            DECIMAL(18,2) NOT NULL,
  reason            TEXT          NOT NULL,
  status            ENUM('pending','approved','rejected','applied') NOT NULL DEFAULT 'pending',
  requested_by      CHAR(36)          NULL,
  requested_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  approved_by       CHAR(36)          NULL,
  approved_at       DATETIME(3)       NULL,
  applied_at        DATETIME(3)       NULL,
  rejection_reason  TEXT              NULL,
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY ix_wo_loan   (loan_id),
  KEY ix_wo_status (status),
  CONSTRAINT fk_wo_loan      FOREIGN KEY (loan_id)      REFERENCES loans(id) ON DELETE CASCADE,
  CONSTRAINT fk_wo_requester FOREIGN KEY (requested_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_wo_approver  FOREIGN KEY (approved_by)  REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS loan_provisions (
  loan_id      CHAR(36)      NOT NULL PRIMARY KEY,
  stage        TINYINT       NOT NULL,
  dpd          INT           NOT NULL DEFAULT 0,
  exposure     DECIMAL(18,2) NOT NULL DEFAULT 0,
  pd_rate      DECIMAL(7,4)  NOT NULL,
  lgd_rate     DECIMAL(7,4)  NOT NULL DEFAULT 0.45,
  ecl_amount   DECIMAL(18,2) NOT NULL,
  computed_at  DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_prov_loan FOREIGN KEY (loan_id) REFERENCES loans(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- ============================================================
-- COLLECTIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS collection_actions (
  id              CHAR(36)    NOT NULL PRIMARY KEY,
  loan_id         CHAR(36)    NOT NULL,
  customer_id     CHAR(36)    NOT NULL,
  channel         ENUM('call','sms','email','visit','letter','whatsapp','other') NOT NULL,
  outcome         ENUM('reached','no_answer','promise','refused','wrong_number','paid','other') NOT NULL,
  notes           TEXT            NULL,
  next_action_at  DATE            NULL,
  performed_by    CHAR(36)        NULL,
  performed_at    DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_ca_loan (loan_id),
  KEY ix_ca_perf (performed_at),
  CONSTRAINT fk_ca_loan FOREIGN KEY (loan_id)      REFERENCES loans(id)     ON DELETE CASCADE,
  CONSTRAINT fk_ca_cust FOREIGN KEY (customer_id)  REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_ca_user FOREIGN KEY (performed_by) REFERENCES users(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS promises_to_pay (
  id                CHAR(36)      NOT NULL PRIMARY KEY,
  loan_id           CHAR(36)      NOT NULL,
  customer_id       CHAR(36)      NOT NULL,
  promised_amount   DECIMAL(18,2) NOT NULL,
  promised_date     DATE          NOT NULL,
  status            ENUM('open','kept','broken','partial','cancelled') NOT NULL DEFAULT 'open',
  resolved_amount   DECIMAL(18,2) NOT NULL DEFAULT 0,
  resolved_at       DATETIME(3)       NULL,
  recorded_by       CHAR(36)          NULL,
  notes             TEXT              NULL,
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY ix_ptp_loan (loan_id),
  KEY ix_ptp_status (status),
  CONSTRAINT fk_ptp_loan FOREIGN KEY (loan_id)     REFERENCES loans(id)     ON DELETE CASCADE,
  CONSTRAINT fk_ptp_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE CASCADE,
  CONSTRAINT fk_ptp_user FOREIGN KEY (recorded_by) REFERENCES users(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS guarantor_followups (
  id              CHAR(36)    NOT NULL PRIMARY KEY,
  loan_id         CHAR(36)    NOT NULL,
  guarantor_id    CHAR(36)    NOT NULL,
  status          ENUM('pending','contacted','committed','refused','unreachable','resolved') NOT NULL DEFAULT 'pending',
  contacted_at    DATETIME(3)     NULL,
  next_action_at  DATE            NULL,
  notes           TEXT            NULL,
  performed_by    CHAR(36)        NULL,
  created_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at      DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  KEY ix_gf_loan (loan_id),
  CONSTRAINT fk_gf_loan FOREIGN KEY (loan_id)      REFERENCES loans(id)      ON DELETE CASCADE,
  CONSTRAINT fk_gf_guar FOREIGN KEY (guarantor_id) REFERENCES guarantors(id) ON DELETE CASCADE,
  CONSTRAINT fk_gf_user FOREIGN KEY (performed_by) REFERENCES users(id)      ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- ACCOUNTING — chart of accounts + journal entries
-- ============================================================
CREATE TABLE IF NOT EXISTS chart_of_accounts (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  code          VARCHAR(20)  NOT NULL,
  name          VARCHAR(255) NOT NULL,
  account_class ENUM('asset','liability','equity','income','expense') NOT NULL,
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY uq_coa_code (code)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS journal_entries (
  id              CHAR(36)      NOT NULL PRIMARY KEY,
  entry_date      DATE          NOT NULL,
  reference       VARCHAR(100)  NOT NULL,
  description     TEXT              NULL,
  debit_account   CHAR(36)      NOT NULL,
  credit_account  CHAR(36)      NOT NULL,
  amount          DECIMAL(18,2) NOT NULL,
  source_table    VARCHAR(100)      NULL,
  source_id       CHAR(36)          NULL,
  created_by      CHAR(36)          NULL,
  created_at      DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_je_date (entry_date),
  KEY ix_je_dr   (debit_account),
  KEY ix_je_cr   (credit_account),
  KEY ix_je_src  (source_table, source_id),
  CONSTRAINT fk_je_dr   FOREIGN KEY (debit_account)  REFERENCES chart_of_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_je_cr   FOREIGN KEY (credit_account) REFERENCES chart_of_accounts(id) ON DELETE RESTRICT,
  CONSTRAINT fk_je_user FOREIGN KEY (created_by)     REFERENCES users(id)             ON DELETE SET NULL,
  CONSTRAINT ck_je_diff CHECK (debit_account <> credit_account),
  CONSTRAINT ck_je_amt  CHECK (amount > 0)
) ENGINE=InnoDB;

-- ============================================================
-- AUDIT (hash-chained, sequence-ordered)
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_log (
  seq         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  id          CHAR(36)     NOT NULL,
  user_id     CHAR(36)         NULL,
  action      VARCHAR(20)  NOT NULL,
  table_name  VARCHAR(100) NOT NULL,
  record_id   CHAR(36)         NULL,
  old_data    JSON             NULL,
  new_data    JSON             NULL,
  prev_hash   VARBINARY(32)    NULL,
  entry_hash  VARBINARY(32)    NULL,
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_audit_table (table_name, record_id),
  KEY ix_audit_user  (user_id),
  KEY ix_audit_time  (created_at)
) ENGINE=InnoDB;

-- ============================================================
-- NOTIFICATIONS / QUEUES
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id          CHAR(36)    NOT NULL PRIMARY KEY,
  user_id     CHAR(36)    NOT NULL,
  title       VARCHAR(255) NOT NULL,
  body        TEXT            NULL,
  link        VARCHAR(500)    NULL,
  category    VARCHAR(50)     NULL,
  is_read     TINYINT(1)  NOT NULL DEFAULT 0,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_notif_user (user_id, is_read),
  CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS sms_queue (
  id          CHAR(36)    NOT NULL PRIMARY KEY,
  to_phone    VARCHAR(50) NOT NULL,
  message     TEXT        NOT NULL,
  status      ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
  attempts    INT         NOT NULL DEFAULT 0,
  last_error  TEXT            NULL,
  customer_id CHAR(36)        NULL,
  loan_id     CHAR(36)        NULL,
  sent_at     DATETIME(3)     NULL,
  created_at  DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_sms_status (status),
  CONSTRAINT fk_sms_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_sms_loan FOREIGN KEY (loan_id)     REFERENCES loans(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS email_queue (
  id          CHAR(36)     NOT NULL PRIMARY KEY,
  to_email    VARCHAR(255) NOT NULL,
  subject     VARCHAR(500) NOT NULL,
  body        TEXT         NOT NULL,
  status      ENUM('pending','sent','failed') NOT NULL DEFAULT 'pending',
  attempts    INT          NOT NULL DEFAULT 0,
  last_error  TEXT             NULL,
  customer_id CHAR(36)         NULL,
  loan_id     CHAR(36)         NULL,
  sent_at     DATETIME(3)      NULL,
  created_at  DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY ix_email_status (status),
  CONSTRAINT fk_email_cust FOREIGN KEY (customer_id) REFERENCES customers(id) ON DELETE SET NULL,
  CONSTRAINT fk_email_loan FOREIGN KEY (loan_id)     REFERENCES loans(id)     ON DELETE SET NULL
) ENGINE=InnoDB;

-- ============================================================
-- MIGRATIONS BOOKKEEPING
-- ============================================================
CREATE TABLE IF NOT EXISTS schema_migrations (
  name       VARCHAR(255) NOT NULL PRIMARY KEY,
  applied_at DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB;
